// Vivere Assistito — Affiliate links registry (single file to edit)
//
// HOW TO USE
// - Replace each "DA DEFINIRE" with your real tracking URL.
// - You can keep multiple options per key (Amazon + alternative merchants).
// - The site will automatically pick the first available URL.
// - If everything is still "DA DEFINIRE", the button will route to:
//   affiliazioni.html#in-attivazione

// Each key can be:
// 1) a string URL
// 2) an object { label, url }
// 3) an array of { label, url } (recommended)

window.AFF_LINKS = {
  // ======== GLOBAL ENTRY POINTS (cards in pages) ========
  // Post-ictus a casa — cards
  post_marketplace: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Semprefarmacia (Awin)", url: "DA DEFINIRE" },
    { label: "Canlua (Tradedoubler)", url: "DA DEFINIRE" }
  ],
  post_partner: [
    { label: "Partner assistenza domiciliare", url: "DA DEFINIRE" },
    { label: "Partner riabilitazione domiciliare", url: "DA DEFINIRE" }
  ],
  post_guide: [
    { label: "Guida Post-ictus", url: "DA DEFINIRE" }
  ],

  // Bagno sicuro — cards
  bagno_marketplace: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "ManoMano (Awin)", url: "DA DEFINIRE" },
    { label: "Leroy Merlin (Awin)", url: "DA DEFINIRE" }
  ],
  bagno_partner: [
    { label: "Partner installazione bagno sicuro", url: "DA DEFINIRE" },
    { label: "Partner consulenza ausili", url: "DA DEFINIRE" }
  ],
  bagno_guide: [
    { label: "Guida Bagno sicuro", url: "DA DEFINIRE" }
  ],

  // ======== RECOMMENDATION BUTTONS (risultato-post-ictus) ========
  // These keys are generated by the app: aff_<FOCUS>_<IDX>
  // MOBILITA (3)
  aff_MOBILITA_0: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Alternative", url: "DA DEFINIRE" }
  ],
  aff_MOBILITA_1: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Alternative", url: "DA DEFINIRE" }
  ],
  aff_MOBILITA_2: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Alternative", url: "DA DEFINIRE" }
  ],

  // BAGNO (3)
  aff_BAGNO_0: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "ManoMano", url: "DA DEFINIRE" }
  ],
  aff_BAGNO_1: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Semprefarmacia", url: "DA DEFINIRE" }
  ],
  aff_BAGNO_2: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Alternative", url: "DA DEFINIRE" }
  ],

  // LETTO (6)
  aff_LETTO_0: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Alternative", url: "DA DEFINIRE" }
  ],
  aff_LETTO_1: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Alternative", url: "DA DEFINIRE" }
  ],
  aff_LETTO_2: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Alternative", url: "DA DEFINIRE" }
  ],
  aff_LETTO_3: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Alternative", url: "DA DEFINIRE" }
  ],
  aff_LETTO_4: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Alternative", url: "DA DEFINIRE" }
  ],
  aff_LETTO_5: [
    { label: "Amazon", url: "DA DEFINIRE" },
    { label: "Alternative", url: "DA DEFINIRE" }
  ]
};
